### PR TITLE
Create migrations

### PR DESCRIPTION
**Pull request by AbdelrahmanRabiee**
i added some fixes to support django 2.0 
command syncdb not working any more 
i add migrations/__init__.py 
so that user can makemigartions and migrate to run project

### CODE REVIEW

**Comment by AlSayedGamal** [comment]
Do you mean migrations/__init__.py ?

**Comment by AbdelrahmanRabiee** [comment]
yup i meant that

**Comment by AbdelrahmanRabiee** [comment]
in READ.ME there is a command "python ./manage.py syncdb" 
he is not working any more 
i added "migrations/__init__.py" 
so that user can run cmmand "python ./manage.py migrate"

**Comment by const-cloudinary** [comment]
What I see in this PR, is that you added an empty file called `migrations`. I'm not sure how it helped you in this case, for me everything works fine without `migrations` directory, since this project has no migrations. And thanks for pointing out outdated README, I'll update it.

**Pull request closed without merging**
